# Use the official Apache HTTP Server image as the base image
FROM httpd:alpine

# Copy the local index.html to the Apache web directory
COPY index.html /usr/local/apache2/htdocs/

# Expose port 80 to allow access to the web server
EXPOSE 80